FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm cache clean --force && npm ci

COPY . .

RUN npm run build


RUN ls -la /app/dist/


FROM nginx:alpine


RUN rm /etc/nginx/conf.d/default.conf


COPY nginx.conf /etc/nginx/conf.d/default.conf


COPY --from=build /app/dist /usr/share/nginx/html

RUN ls -la /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]